
const SESSION_COOKIE="scc_session",CSRF_COOKIE="scc_csrf";
const SEC={"X-Frame-Options":"DENY","X-Content-Type-Options":"nosniff","Referrer-Policy":"no-referrer","X-Robots-Tag":"noindex, nofollow","Permissions-Policy":"camera=(), microphone=(), geolocation=()","Content-Security-Policy":"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; connect-src 'self' https: wss:; frame-ancestors 'none'; base-uri 'self'; form-action 'self'"};
const OWNER=new Set(["SET_AGENT_CONFIG","RUN_OLD_VERSION_CLEANUP","GET_CLEANUP_REPORT","DELETE_RULE","DELETE_PLAN","SET_BROWSER_PAIRING"]);
const ADMIN=new Set(["PING","GET_AGENT_HEALTH","GET_WINDOWS_STATE","GET_AGENT_CONFIG","GET_AGENT_LOGS","GET_RECENT_ERRORS","CLEAR_ERRORS","START_WINDOWS_LIVE","STOP_WINDOWS_LIVE","WINDOWS_CAPTURE_ONCE","SET_LIVE_QUALITY","SET_LIVE_FPS","SET_LIVE_SCALE","SET_LOW_BANDWIDTH_MODE","UNSET_LOW_BANDWIDTH_MODE","GET_BANDWIDTH_MODE","GET_PROCESS_LIST","WINDOWS_CLOSE_PROCESS","WINDOWS_CLOSE_PROCESS_CONTAINS","WINDOWS_CLOSE_PROCESS_GROUP","GET_ACTIVE_WINDOW","GET_OPEN_WINDOWS","GET_BROWSER_PAIRING","OPEN_URL","GET_TABS","CLOSE_TAB","RELOAD_TAB","START_SINGLE_TASK","STOP_SINGLE_TASK","PAUSE_SCREEN","UNPAUSE_SCREEN","START_LIVE","STOP_LIVE","CAPTURE_ONCE","TROUBLESHOOT","RESET_ALLOW_ALL"]);
const VIEWER=new Set(["PING","GET_AGENT_HEALTH","GET_WINDOWS_STATE","GET_PROCESS_LIST","GET_ACTIVE_WINDOW","GET_TABS","GET_AGENT_LOGS","GET_RECENT_ERRORS","GET_BANDWIDTH_MODE"]);
export default{async fetch(req,env,ctx){try{return await route(req,env,ctx)}catch(e){console.error(e);return text("Internal error",500)}}};
async function route(req,env,ctx){const u=new URL(req.url),p=u.pathname;
 if(p==="/robots.txt")return text("User-agent: *\nDisallow: /\n",200,{"Content-Type":"text/plain"});
 if(p==="/healthz")return json({ok:true,service:"study-auth-gateway"});
 if(p==="/login"&&req.method==="GET")return loginPage();
 if(p==="/login"&&req.method==="POST")return login(req,env);
 if(p==="/logout")return logout(req,env);
 if(p==="/auth/me")return me(req,env);
 if(p==="/api/csrf")return csrf(req,env);
 const user=await session(req,env);
 if(!user){ if(p==="/")return html("<!doctype html><html><head><title></title></head><body></body></html>"); return text("Unauthorized",401); }
 if(p.startsWith("/api/")){ if(["POST","PUT","PATCH","DELETE"].includes(req.method)&&!(await verifyCsrf(req,user)))return json({ok:false,error:"csrf_failed"},403); return proxyApi(req,env,user); }
 if(p.startsWith("/ws/"))return proxyWs(req,env,user);
 if(env.ASSETS)return withSec(await env.ASSETS.fetch(req));
 return text("Assets binding missing",500);
}
async function login(req,env){const ip=await ipHash(req,env); if(await limited(env,ip))return loginPage("Too many attempts. Try later.",429);
 const ct=req.headers.get("content-type")||"";let b;if(ct.includes("json"))b=await req.json();else{const fd=await req.formData();b={username:fd.get("username"),password:fd.get("password")}}
 const username=String(b.username||"").trim().toLowerCase(),password=String(b.password||"");
 const user=await env.DB.prepare("SELECT * FROM users WHERE username=? AND enabled=1").bind(username).first();
 if(!user){await attempt(env,ip,username,false);await audit(env,null,"login_failed",req,{username});return loginPage("Invalid username or password.",401)}
 const h=await pbkdf2(password,user.password_salt,Number(user.password_iterations||210000));
 if(!safeEq(h,user.password_hash)){await attempt(env,ip,username,false);await audit(env,user.id,"login_failed",req,{username});return loginPage("Invalid username or password.",401)}
 await attempt(env,ip,username,true);
 const token=rand(32),sh=await sha256(token),csrfTok=rand(24),ch=await sha256(csrfTok),now=Date.now(),ttl=Number(env.SESSION_TTL_HOURS||12),exp=now+ttl*3600*1000;
 await env.DB.prepare("INSERT INTO sessions(user_id,session_hash,csrf_hash,created_at,expires_at,user_agent,ip_hash,revoked) VALUES(?,?,?,?,?,?,?,0)").bind(user.id,sh,ch,now,exp,req.headers.get("user-agent")||"",ip).run();
 await env.DB.prepare("UPDATE users SET last_login_at=? WHERE id=?").bind(now,user.id).run(); await audit(env,user.id,"login_success",req,{username});
 const head=new Headers({Location:"/"}); setCookie(head,SESSION_COOKIE,token,ttl*3600,true); setCookie(head,CSRF_COOKIE,csrfTok,ttl*3600,false); return withSec(new Response(null,{status:302,headers:head}));
}
async function logout(req,env){const u=await session(req,env);if(u?.session){await env.DB.prepare("UPDATE sessions SET revoked=1 WHERE id=?").bind(u.session.id).run();await audit(env,u.id,"logout",req,{})}const h=new Headers({Location:"/login"});clearCookie(h,SESSION_COOKIE);clearCookie(h,CSRF_COOKIE);return withSec(new Response(null,{status:302,headers:h}))}
async function me(req,env){const u=await session(req,env);if(!u)return json({ok:false,authenticated:false},401);return json({ok:true,authenticated:true,user:{id:u.id,username:u.username,role:u.role},csrf:cookie(req,CSRF_COOKIE)||null})}
async function csrf(req,env){const u=await session(req,env);if(!u)return json({ok:false},401);return json({ok:true,csrf:cookie(req,CSRF_COOKIE)||null})}
async function session(req,env){const t=cookie(req,SESSION_COOKIE);if(!t)return null;const sh=await sha256(t),now=Date.now();const r=await env.DB.prepare("SELECT s.*,u.username,u.role,u.enabled FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.session_hash=? AND s.revoked=0 AND s.expires_at>? AND u.enabled=1").bind(sh,now).first(); if(!r)return null;return {id:r.user_id,username:r.username,role:r.role||"viewer",session:r}}
async function verifyCsrf(req,u){const s=req.headers.get("X-CSRF-Token")||"",c=cookie(req,CSRF_COOKIE)||"";if(!s||!c||s!==c)return false;return safeEq(await sha256(s),u.session.csrf_hash)}
async function proxyApi(req,env,user){const src=new URL(req.url),base=new URL(env.BACKEND_BASE_URL),target=new URL(src.pathname+src.search,base);if(env.BACKEND_API_KEY)target.searchParams.set("key",env.BACKEND_API_KEY);let body=null,cmd=null;if(["POST","PUT","PATCH"].includes(req.method)){body=await req.text();cmd=extractCmdText(body);if(cmd&&!allowed(cmd,user.role)){await audit(env,user.id,"command_blocked",req,{cmd});return json({ok:false,error:"command_not_allowed",cmd},403)}}const h=new Headers(req.headers);h.delete("cookie");h.set("X-Study-User",user.username);h.set("X-Study-Role",user.role);if(env.BACKEND_API_KEY)h.set("X-API-Key",env.BACKEND_API_KEY);const resp=await fetch(target,{method:req.method,headers:h,body});if(cmd)await audit(env,user.id,"command_sent",req,{cmd,status:resp.status});return withSec(resp)}
async function proxyWs(req,env,user){if(req.headers.get("Upgrade")!=="websocket")return text("Expected websocket",400);const src=new URL(req.url),base=new URL(env.BACKEND_BASE_URL);base.protocol=base.protocol==="https:"?"wss:":"ws:";const target=new URL(src.pathname+src.search,base);if(env.BACKEND_API_KEY)target.searchParams.set("key",env.BACKEND_API_KEY);target.searchParams.set("role","admin");target.searchParams.set("adminUser",user.username);const pair=new WebSocketPair(),client=pair[0],server=pair[1];server.accept();const br=await fetch(target,{headers:{Upgrade:"websocket"}});if(br.status!==101||!br.webSocket){server.send(JSON.stringify({type:"error",error:"backend_ws_failed",status:br.status}));server.close(1011,"backend ws failed");return new Response(null,{status:101,webSocket:client})}const bws=br.webSocket;bws.accept();server.addEventListener("message",async ev=>{try{const text=typeof ev.data==="string"?ev.data:"",cmd=extractCmdText(text);if(cmd&&!allowed(cmd,user.role)){server.send(JSON.stringify({type:"error",error:"command_not_allowed",cmd}));await audit(env,user.id,"ws_command_blocked",req,{cmd});return}if(cmd)await audit(env,user.id,"ws_command_sent",req,{cmd});bws.send(ev.data)}catch{server.send(JSON.stringify({type:"error",error:"ws_proxy_client_error"}))}});bws.addEventListener("message",ev=>{try{server.send(ev.data)}catch{}});server.addEventListener("close",()=>{try{bws.close()}catch{}});bws.addEventListener("close",()=>{try{server.close()}catch{}});return new Response(null,{status:101,webSocket:client})}
function extractCmdText(t){try{return extractCmd(JSON.parse(t))}catch{return null}}function extractCmd(o){if(!o||typeof o!=="object")return null;if(typeof o.command==="string")return o.command.toUpperCase();if(o.command?.type)return String(o.command.type).toUpperCase();if(o.commandType)return String(o.commandType).toUpperCase();if(o.action)return String(o.action).toUpperCase();if(o.action_type)return String(o.action_type).toUpperCase();return null}
function allowed(c,role){c=String(c||"").toUpperCase();if(role==="owner")return OWNER.has(c)||ADMIN.has(c)||VIEWER.has(c);if(role==="admin")return ADMIN.has(c)||VIEWER.has(c);return VIEWER.has(c)}
async function limited(env,ip){const cut=Date.now()-600000,r=await env.DB.prepare("SELECT COUNT(*) c FROM login_attempts WHERE ip_hash=? AND success=0 AND created_at>?").bind(ip,cut).first();return Number(r?.c||0)>=5}
async function attempt(env,ip,u,s){await env.DB.prepare("INSERT INTO login_attempts(ip_hash,username,success,created_at) VALUES(?,?,?,?)").bind(ip,u||"",s?1:0,Date.now()).run()}
async function audit(env,uid,event,req,det){try{await env.DB.prepare("INSERT INTO audit_logs(user_id,event,ip_hash,user_agent_hash,details_json,created_at) VALUES(?,?,?,?,?,?)").bind(uid,event,await ipHash(req,env),await sha256(req.headers.get("user-agent")||""),JSON.stringify(det||{}),Date.now()).run()}catch(e){console.error("audit failed",e)}}
async function ipHash(req,env){const ip=req.headers.get("CF-Connecting-IP")||req.headers.get("x-forwarded-for")||"unknown";return sha256(`${env.IP_HASH_SECRET||"change-me"}:${ip}`)}
async function pbkdf2(pass,saltHex,it){const enc=new TextEncoder(),key=await crypto.subtle.importKey("raw",enc.encode(pass),"PBKDF2",false,["deriveBits"]),bits=await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt:hexBytes(saltHex),iterations:it},key,256);return hex(new Uint8Array(bits))}
async function sha256(x){const d=typeof x==="string"?new TextEncoder().encode(x):x;return hex(new Uint8Array(await crypto.subtle.digest("SHA-256",d)))}
function safeEq(a,b){if(!a||!b||a.length!==b.length)return false;let o=0;for(let i=0;i<a.length;i++)o|=a.charCodeAt(i)^b.charCodeAt(i);return o===0}function rand(n=32){const a=new Uint8Array(n);crypto.getRandomValues(a);return hex(a)}function hex(a){return [...a].map(b=>b.toString(16).padStart(2,"0")).join("")}function hexBytes(h){const a=new Uint8Array(h.length/2);for(let i=0;i<a.length;i++)a[i]=parseInt(h.slice(i*2,i*2+2),16);return a}
function cookie(req,n){const c=req.headers.get("Cookie")||"";return c.split(";").map(x=>x.trim()).find(x=>x.startsWith(n+"="))?.split("=").slice(1).join("=")||""}function setCookie(h,n,v,max,http=true){const p=[`${n}=${v}`,"Path=/","Secure","SameSite=Lax",`Max-Age=${max}`];if(http)p.push("HttpOnly");h.append("Set-Cookie",p.join("; "))}function clearCookie(h,n){h.append("Set-Cookie",`${n}=; Path=/; Secure; SameSite=Lax; Max-Age=0; HttpOnly`)}
function loginPage(err="",status=200){return html(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Login</title><style>body{margin:0;min-height:100vh;display:grid;place-items:center;background:#020617;color:#e5e7eb;font-family:system-ui,Arial}form{width:min(420px,92vw);background:#0f172a;border:1px solid #1e293b;border-radius:22px;padding:28px;box-shadow:0 20px 80px #0008}h1{margin:0 0 8px;font-size:24px}p{color:#94a3b8}input,button{width:100%;box-sizing:border-box;border-radius:12px;padding:13px;margin:8px 0;border:1px solid #334155;background:#111827;color:#e5e7eb}button{background:#2563eb;border:0;font-weight:800;cursor:pointer}.err{color:#fecaca;background:#450a0a;border:1px solid #7f1d1d;padding:10px;border-radius:12px}</style></head><body><form method="POST" action="/login"><h1>Study Command Center</h1><p>Authorized access only.</p>${err?`<div class="err">${esc(err)}</div>`:""}<input name="username" placeholder="Username" required autofocus><input name="password" type="password" placeholder="Password" required><button>Login</button></form></body></html>`,status)}
function html(b,s=200,h={}){return withSec(new Response(b,{status:s,headers:{"Content-Type":"text/html; charset=utf-8",...h}}))}function json(o,s=200,h={}){return withSec(new Response(JSON.stringify(o),{status:s,headers:{"Content-Type":"application/json",...h}}))}function text(b,s=200,h={}){return withSec(new Response(b,{status:s,headers:{"Content-Type":"text/plain; charset=utf-8",...h}}))}function withSec(r){const h=new Headers(r.headers);for(const[k,v]of Object.entries(SEC))h.set(k,v);return new Response(r.body,{status:r.status,statusText:r.statusText,headers:h})}function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
